=== fernandozamoraj/XML-Project-For-Masters-Course/XML Project 2May2010/Source Code/PicassosInventorySystem/Data/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Fernando Zamora (McLane Advanced Technologies) -->
<!--W3C Schema generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ProductGraph">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Catalog">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CatalogItems">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="CatalogItem" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Description" type="xs:string"/>
													<xs:element name="UnitCost" type="xs:double"/>
													<xs:element name="Comments" type="xs:string"/>
												</xs:sequence>
												<xs:attribute name="VendorId" type="xs:IDREF" use="required"/>
												<xs:attribute name="VendorAssignedProductId" type="xs:string" use="required"/>
												<xs:attribute name="Id" type="xs:ID" use="required"/>
												
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="BoxedItems">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="BoxedItem" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Description" type="xs:string"/>
													<xs:element name="UnitCost" type="xs:double"/>
													<xs:element name="Comments" type="xs:string"/>
													<xs:element name="BoxCost" type="xs:int"/>
													<xs:element name="UnitsInBox" type="xs:int"/>
												</xs:sequence>
												<xs:attribute name="VendorId" type="xs:IDREF" use="required"/>
												<xs:attribute name="VendorAssignedProductId" type="xs:string" use="required"/>
												<xs:attribute name="Id" type="xs:ID" use="required"/>
												
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="VolumeItems">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="VolumeItem" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Description" type="xs:string"/>
													<xs:element name="UnitCost" type="xs:double"/>
													<xs:element name="Comments" type="xs:string"/>
													<xs:element name="MinimumVolume" type="xs:int"/>
													<xs:element name="UnitOfMeasure" type="xs:string"/>
													
												</xs:sequence>
												<xs:attribute name="VendorId" type="xs:IDREF" use="required"/>
												<xs:attribute name="VendorAssignedProductId" type="xs:string" use="required"/>
												<xs:attribute name="Id" type="xs:ID" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Inventory">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="InventoryItems">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="InventoryItem" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="QtyOnHand" type="xs:int"/>
													<xs:element name="ReOrderPoint" type="xs:int"/>
													<xs:element name="ReOrderQuantity" type="xs:int"/>
													<xs:element name="Comments" type="xs:string"/>
												</xs:sequence>
												<xs:attribute name="LocationId" type="xs:IDREF" use="required"/>
												<xs:attribute name="Id" type="xs:ID" use="required"/>
												<xs:attribute name="CatalogItemId" type="xs:IDREF" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Locations">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Location" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string"/>
													<xs:element name="Description" type="xs:string"/>
												</xs:sequence>
												<xs:attribute name="Id" type="xs:ID" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Suppliers">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Vendor" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="xs:string"/>
										<xs:element name="PointOfContact" type="xs:string"/>
										<xs:element name="PhoneNumber" type="xs:string"/>
										<xs:element name="Comments" type="xs:string"/>
										<xs:element name="Addresses">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Address">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Street" type="xs:string"/>
																<xs:element name="City" type="xs:string"/>
																<xs:element name="State" type="xs:string"/>
																<xs:element name="Zip" type="xs:string"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Id" type="xs:ID" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== fernandozamoraj/XML-Project-For-Masters-Course/XML Project 2May2010/Source Code/PicassosInventorySystem/Data/MarksDemo.xml
<ProductGraph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">
   <Catalog>
      <CatalogItems>
         <CatalogItem VendorId="vendor0000000001"  Id="cat0000000003"  VendorAssignedProductId="MWCG3240" >
            <Description>MAT White Core Green 32x40</Description>
            <UnitCost>2.50</UnitCost>
            <Comments/>
         </CatalogItem>
      </CatalogItems>
      <BoxedItems>
         <BoxedItem VendorId="vendor0000000001"  Id="cat0000000004"  VendorAssignedProductId="GLASS16x20" >
            <Description>Glass</Description>
            <UnitCost>2.5</UnitCost>
            <Comments/>
            <BoxCost>25</BoxCost>
            <UnitsInBox>10</UnitsInBox>
         </BoxedItem>
         <BoxedItem VendorId="vendor0000000002"  Id="cat0000000006"  VendorAssignedProductId="GLASS16x20" >
            <Description>Glass</Description>
            <UnitCost>3</UnitCost>
            <Comments/>
            <BoxCost>30</BoxCost>
            <UnitsInBox>10</UnitsInBox>
         </BoxedItem>
      </BoxedItems>
      <VolumeItems>
         <VolumeItem VendorId="vendor0000000002"  Id="cat0000000007"  VendorAssignedProductId="MGL3INW" >
            <Description>Molding Gold Leaf 3in Wide</Description>
            <UnitCost>4</UnitCost>
            <Comments/>
            <MinimumVolume>10</MinimumVolume>
            <UnitOfMeasure>Foot</UnitOfMeasure>
         </VolumeItem>
      </VolumeItems>
   </Catalog>
   <Inventory>
      <InventoryItems>
         <InventoryItem Id="inv0000000005"  LocationId="loc0000000009"  CatalogItemId="cat0000000003" >
            <QtyOnHand>10</QtyOnHand>
            <ReOrderPoint>10</ReOrderPoint>
            <ReOrderQuantity>10</ReOrderQuantity>
            <Comments>Please store in upper bins to preven damage by flood</Comments>
         </InventoryItem>
         <InventoryItem Id="inv0000000008"  LocationId="loc0000000009"  CatalogItemId="cat0000000007" >
            <QtyOnHand>20</QtyOnHand>
            <ReOrderPoint>10</ReOrderPoint>
            <ReOrderQuantity>10</ReOrderQuantity>
            <Comments>Please store in upper bins to preven damage by flood</Comments>
         </InventoryItem>
      </InventoryItems>
      <Locations>
         <Location Id="loc0000000009" >
            <Name>Back Room</Name>
            <Description>Back Room of Store Bin1</Description>
         </Location>
      </Locations>
   </Inventory>
   <Suppliers>
      <Vendor Id="vendor0000000001" >
         <Name>Hobby Lobby Temple</Name>
         <PointOfContact>Jeff</PointOfContact>
         <PhoneNumber>254 333-5555</PhoneNumber>
         <Comments>Located Now by Ross</Comments>
         <Addresses>
            <Address>
               <Street>123 some street</Street>
               <City>Temple</City>
               <State>TX</State>
               <Zip>76543</Zip>
            </Address>
         </Addresses>
      </Vendor>
      <Vendor Id="vendor0000000002" >
         <Name>Hobby Lobby Killeen</Name>
         <PointOfContact>Jeff</PointOfContact>
         <PhoneNumber>254 333-5555</PhoneNumber>
         <Comments>Located Now by Ross</Comments>
         <Addresses>
            <Address>
               <Street>123 some street</Street>
               <City>Killeen</City>
               <State>TX</State>
               <Zip>76543</Zip>
            </Address>
         </Addresses>
      </Vendor>
   </Suppliers>
</ProductGraph>
