=== fernandozamoraj/XML-Project-For-Masters-Course/XML Project 2May2010/XML Artifacts/Paper/ProjectPaper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="TitlePage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Title"/>
				<xs:element ref="Members"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Title">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Main"/>
				<xs:element ref="Sub"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubSectionHeader" type="xs:string"/>
	<xs:element name="SubSection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SubSectionHeader"/>
				<xs:element ref="Fragment" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Sub" type="xs:string"/>
	<xs:element name="Section">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Header"/>
				<xs:element ref="SubSection" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ReferenceSegment">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="italic" type="xs:string" use="required"/>
					<xs:attribute name="bold" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Reference">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ReferenceSegment" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Paragraph" type="xs:string"/>
	<xs:element name="Members">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Member" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Member" type="xs:string"/>
	<xs:element name="Main" type="xs:string"/>
	<xs:element name="Item">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="level" type="xs:int"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Introduction">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Header"/>
				<xs:element ref="Fragment" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Header" type="xs:string"/>
	<xs:element name="Fragment">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="BulletedList"/>
				<xs:element ref="Figure"/>
				<xs:element ref="Paragraph"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="FileName" type="xs:string"/>
	<xs:element name="Figure">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FileName"/>
				<xs:element ref="Caption"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ConclusionHeader" type="xs:string"/>
	<xs:element name="Conclusion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ConclusionHeader"/>
				<xs:element ref="Fragment" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ChicagoStylePaper">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TitlePage"/>
				<xs:element ref="Abstract"/>
				<xs:element ref="Body"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Caption" type="xs:string"/>
	<xs:element name="BulletedList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Item" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="numbered" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Body">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Introduction"/>
				<xs:element ref="Section" maxOccurs="unbounded"/>
				<xs:element ref="Conclusion"/>
				<xs:element ref="Bibliography"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Bibliography">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Reference" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AbstractHeader" type="xs:string"/>
	<xs:element name="Abstract">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AbstractHeader"/>
				<xs:element ref="Fragment" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== fernandozamoraj/XML-Project-For-Masters-Course/XML Project 2May2010/XML Artifacts/Paper/ProjectPaper.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="PaperToHtml.xsl"?> 
<ChicagoStylePaper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ProjectPaper.xsd">
  <TitlePage>
    <Title>
      <Main>Picasso's Inventory System:</Main>
      <Sub>A Project That Leverages XML to Create, Save, Query, and Display a System’s Inventory</Sub>
    </Title>
    <Members>
      <Member>Fernando Zamora</Member>
      <Member>Letitia Murdoch</Member>
      <Member>Manfred Ayers</Member>
      <Member>Mark Thompson</Member>
      <Member>Department of Business</Member>
      <Member>CIS 545 Extensible Markup Language</Member>
      <Member>May 1, 2010</Member>
    </Members>
  </TitlePage>
  <Abstract>
    <AbstractHeader>Abstract</AbstractHeader>
    <Fragment>
      <Paragraph>
          We wrote this paper as part of a project for an [BOLD]XML[/BOLD] class at the graduate level.  
          The paper consists of three major parts; [BOLD]XML Creation[/BOLD] (including XSDs, CSS, XML), [BOLD]Data Entry Application[/BOLD], and a [BOLD]Paper describing the effort[/BOLD].
            The project is broken down into two major subprojects; the actual inventory for a fictional business and the paper that describes the
            our process details, as well as the schema that this paper will ultimately describe the elements of this paper.  This paper is only a portion of an entire project.              
        </Paragraph>
    </Fragment>
    <Fragment>
      <Paragraph>
        This project consists of the following artifacts that go along with this paper:  
      </Paragraph>
    </Fragment>
    <Fragment>
      <BulletedList>
        <Item level="1">Paper Related Artifacts</Item>
        <Item level="2">ProjectPaper.xml</Item>
        <Item level="2">ProjectPaper.xsd</Item>
        <Item level="2">ProjectPaper.html</Item>
        <Item level="2">PaperToHtml.xsl</Item>
        <Item level="2">Images Folder with the following images</Item>
        <Item level="3">chicagopaperschema.png</Item>
        <Item level="3">htmlscreenshot.png</Item>
        <Item level="3">inventoryschemahighlevel.png</Item>
        <Item level="3">inventoryscreen.png</Item>
        <Item level="3">vendorscreen.png</Item>
        <Item level="3">catalogscreen.png</Item>
        <Item level="1">Inventory Related XML Artifacts</Item>
        <Item level="2">PicassosInventory.xsl</Item>
        <Item level="2">PicassosInventory.xml</Item>
        <Item level="2">PicassosInventory.xsd</Item>
        <Item level="2">PicassosInventory.html</Item>  
        <Item level="2">Images folder with the following:</Item>
        <Item level="3">PicassoLogo.png</Item>
    </BulletedList>
    </Fragment>
  </Abstract>
  <Body>
    <Introduction>
      <Header>Picasso's Frame Shop
      </Header>
      <Fragment>
        <Paragraph>
      This paper is part of a project that will demonstrate how to use Extensible Markup Language [BOLD](XML)[/BOLD] to maintain a small inventory system for a small business.  The objectives of this project are to create the data schemas, the XML documents as well as the data entry system to create and modify the XML document.  Also to be included as part of this project, is a technical document that describes the project and process in creating the inventory system.  A requirement for the technical document is that it must be written in a way that it can be treated as XML data.  This way the XML document can be formatted by an Extensible Stylesheet Language [BOLD](XSL)[/BOLD] document an processing it using what is known as XSL Transformations [BOLD](XSLT)[/BOLD].  This paper will address how the users of this system will be able to create, share, modify and also query the inventory data.  Additionally, this paper will address how the decisions were made the creation all of the artifacts.  This paper will describe the small business that was targeted by the XML data for this project and why.  Finally this paper will briefly described the schemas, content and XSL necessary to transform this paper into a properly formatted [ITALIC]Chicago Manual of Style[/ITALIC] paper
      </Paragraph>
      </Fragment>
      <Fragment>
        <Paragraph>
Since XML is well suited to maintain a small hierarchical database, it has been chosen as the data persistence of choice for this project. Because this paper is a requirement for an XML class the requirements met by this paper were those provided to us.  Nevertheless, XML allows for data definition in the form of Document Type Definition [BOLD](DTD)[/BOLD] documents and XML Schema Definition [BOLD](XSD)[/BOLD] files.  We decided early on that it would be easier to stick with one type of schema language. Therefore the schema language chosen was XSD over DTD.  All of the schemas for this project are XSD files instead of DTD files.      
      </Paragraph>
      </Fragment>
      <Fragment>
        <Paragraph>
        Like any other school project we had some level of freedom in the decision-making process.  Some of this freedom was the ability to choose a small business of our liking.  Because Fernando has extensive experience in the frame making business, we decided to go with a hypothetical small frame shop as our business.  Like all hypothetical business we needed a name for our business and since the business was somewhat related to the art world, we decided to call it Picasso’s.  Therefore, the inventory system was named the Picasso Inventory System.
      </Paragraph>
      </Fragment>
      <Fragment>
        <Paragraph>
        The inventory system is a starting point, rather than a complete solution to the inventory system needs of Picasso frame shop. This is true of the schemas provided in this presentation as well. With that disclaimer out of the way, after careful analysis, the schemas results meet the factors important in maintaining adequate inventory within the shop. The design will allow the Picasso shop to minimize downtime by maintaining adequate inventory, determining pricing requirements, and maintaining our suppliers’ contact information.      
      </Paragraph>
      </Fragment>
    </Introduction>
    <Section>
      <Header>
      The Picasso’s Frame Shop Business
      </Header>
      <SubSection>
        <SubSectionHeader>
          Description of the Business
        </SubSectionHeader>
        <Fragment>
          <Paragraph>
          Picasso’s Frame Shop is a small family owned and operated business.  The business provides custom framing needs for the Temple, Killeen and surrounding areas.  Custom framing provides a higher quality and more elegant solution as well as higher variety for any framed artifact than traditional off-the-shelf frames and mats.  Although off-the-shelf frames meet the requirements for most photographs and many posters, custom framing provides many benefits that off-the-shelf frames and mats cannot provide.  Among these are:
        </Paragraph>
        </Fragment>
        <Fragment>
          <BulletedList>
            <Item>Non-Standard Frame Sizes</Item>
            <Item>Higher Selection of Moulding</Item>
            <Item>Necessary Protection of High Dollar Prints and Photographs</Item>
            <Item>Custom mat cuts not available with off-the-shelf mats</Item>
            <Item>Personalized Color Schemes to fit the framed artifact best</Item>
            <Item>Framing of non-traditional artifacts such as baseballs, flags, awards etc</Item>
          </BulletedList>
        </Fragment>
        <Fragment>
          <Paragraph>Picasso’s cuts every mat, moulding, and sheet of glass to customer desires specifications. For these reasons, the Picasso Frame Shop must be prepared to stock the most common supplies and be able to provide a high selection of custom ordered supplies. Because custom framing competition is quite fierce in the Killeen/Temple area, Picasso’s must maintain the right quantities of the most common supplies. This is all in an effort to provide a quick and efficient turnaround for all orders.  
        </Paragraph>
        </Fragment>
        <Fragment>
          <Paragraph>
          Most orders have a common turnaround span of five days from order to delivery.  In the case where a special order is required, the turnaround time can be as much as two weeks longer than normal.  For that reason, Picasso’s must maintain a high selection of items. This also helps reduce the number of custom vendor orders.  This is all in effort to keep customers coming back to Picasso’s. This lets the customers know that their needs will be met with a high degree of quality and punctuality.  At the same time Picasso’s must also identify those items that simply do not sell well or have been discontinued by the vendor.
        </Paragraph>
        </Fragment>
        <Fragment>
          <Paragraph>
        Custom framing requires a high degree of precision in pricing. This is so that store can be competitive, yet at the same time have the capability to price its services at a profit.  This means that Picasso’s must take all costs incurred into account in order to price the items adequately.  The cost of these supply items is a significant consideration of those costs.
        </Paragraph>
        </Fragment>
      </SubSection>
      <SubSection>
        <SubSectionHeader>
        Framing Equipment and Supplies
        </SubSectionHeader>
        <Fragment>
          <Paragraph>
        The delivery of a custom framing order requires the use of several pieces of equipment and the consumption of several supplies.  The equipment, composed mostly of machines, is maintained by employees.  The adequate inventory of the parts and supplies consumed by these machines, must be maintained on hand to prevent any loss of productivity.
        </Paragraph>
        </Fragment>
